### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by andrivg** [KristinFrida/HBV202G_FINALPPROJECT#1]
## Almennar athugasemdir
- Það vantar URL fyrir license, svo það kemur ekki fram í `mvn site`.
- UML Klasarit er ekki á réttum stað til þess birtast í `mvn site` síðunni. Myndin hefði þurft að vera staðsett í `src\site\resources\umlClassDiagram.png`.
- Javadoc report er ekki í `mvn site`.
- Þú gerir eina scriptu sem hefði í raun átt að vera tvær sitthvorar scripturnar.
	- Ein scripta til þess að búa til jar skrá
	- Önnur scripta til þess að keyra forritið án aðstoðar mvn eða IDE, þ.e. keyra jar skránna sem fyrri scriptan býr til.
- Eftirfarandi plugin eru ekki með nýjustu útgáfu
```sh
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   org.junit.jupiter:junit-jupiter-api .............. 5.10.0 -> 5.11.0-M1
[INFO]   org.junit.jupiter:junit-jupiter-engine ........... 5.10.0 -> 5.11.0-M1
[INFO]   org.openjfx:javafx-controls ............................ 21 -> 23-ea+3
[INFO]   org.openjfx:javafx-fxml ................................ 21 -> 23-ea+3
[INFO]   org.openjfx:javafx-graphics ............................ 21 -> 23-ea+3
```
- Í verkefnalýsingunni er krafa um 4+ klasa. UML klasaritið er bara með 2 klasa og 1 interface sem er ófullnægjandi.
- Tvær public aðferðir í Calculator ekki með javadoc comment heldur venjulegt comment.
## UML
- viðföng eru með java syntax í staðin fyrir UML 2.0 syntax.
### Calculator
- Það er svolítið mikið að gera í `symbols` sem er skrítið að setja í UML klasaritið. Þú átt ekki að tilgreina hvað er innihaldið í fylkinu, heldur þarftu aðeins að setja til um hvað breytan heitir og af hvaða tagi.
	- Ég finn ekki tilviksbreytuna `symbols` í kóðanum heldur.
- Sama á við um restina af tilviksbreytunum í klasanum, þú þarft ekki að tilgreina gildið sem það inniheldur.
- Það vantar static breytuna `differentOperarorsInMath` sem er static, svo hún væri undirstrikuð. Trúlega er þetta `symbols` í UML-inu

### Örvar
- Hefði mátt nota association ör frá `ReiknivelController` til `Reiknivel`. Dependency ör er samt tæknilega séð rétt líka.

**Comment by KristinFrida** [comment]
Takk fyrir svona ýtarlega endurgjöf, ég sé öll klaufamistökin mín núna. Ég þurfti að yfirgefa annað verkefni vegna erfiðleikastigs UML diagram. En það er rétt, ég breytti symbols í differentOperatorsInMath á síðustu stundu til þess að hafa meira lýsandi heiti og gleymdi að breyta UML diagraminu. Síðan yfirsá ég fjóra klasa. En takk samt fyrir önnina, lærði mikið.
